version: "3"

services:
  typescript-nodemon-template:
    image: typescript-nodemon-template
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - "3001:3001"
    network_mode: host
